apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
