replicas: 1
loglevel: "Information"

image:
  repository: openftth/api-gateway
  tag: v1.12.0

eventStoreDatabase:
  name: EVENT_STORE
  username: postgres
  password: postgres

geoDatabase:
  name: OPEN_FTTH
  username: postgres
  password: postgres