replicas: 1
loglevel: "Information"

image:
  repository: openftth/api-gateway
  tag: v4.1.6

eventStoreDatabase:
  name: EVENT_STORE
  username: postgres
  password: postgres

geoDatabase:
  name: OPEN_FTTH
  username: postgres
  password: postgres

resources:
  requests:
    memory: 1500Mi
  limits:
    memory: 2000Mi

typesense:
  host: ""
  port: "80"
  apiKey: ""

auth:
  host: ""
  requireHttps: false
  audience: ""
  enable: true

outageService:
  outageServiceUrl: ""

notificationServer:
  domain: "notification-server"
  port: 80
