replicas: 1
storage: 1Gi
storageClassName: ""
loglevel: "Information"

image:
  repository: openftth/api-gateway
  tag: v1.10.2

eventStoreDatabase:
  name: EVENT_STORE
  username: postgres
  password: postgres

geoDatabase:
  name: OPEN_FTTH
  username: postgres
  password: postgres