apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: kartoza/postgis:12.1
          env:
            - name: WAL_LEVEL
              value: logical
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              name: {{ .Release.Name }}-{{ .Chart.Name }}
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
              mountPath: /{{ .Release.Name }}_{{ .Chart.Name }}_data
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-{{ .Chart.Name }}-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
