apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: kartoza/postgis:12.1
          env:
            - name: POSTGRES_DBNAME
              value: OPEN_FTTH
            - name: WAL_LEVEL
              value: logical
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis
          ports:
            - containerPort: 5432
              name: {{ .Chart.Name }}
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
              mountPath: /var/lib/postgresql/
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-{{ .Chart.Name }}-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.volumeClaim.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.volumeClaim.storage }}
