apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-dshm
          emptyDir:
            medium: Memory
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory}}
          env:
            - name: POSTGRES_DBNAME
              value: OPEN_FTTH
            - name: WAL_LEVEL
              value: logical
            - name: WAL_SIZE
              value: "4GB"
            - name: MIN_WAL_SIZE
              value: "2048MB"
            - name: WAL_SEGSIZE
              value: "1024"
            - name: PG_WAL_KEEP_SEGMENTS
              value: "4"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis
          ports:
            - containerPort: 5432
              name: {{ .Chart.Name }}
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
              mountPath: /var/lib/postgresql/
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-dshm
              mountPath: /dev/shm
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-{{ .Chart.Name }}-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.volumeClaim.storageClassName }}
        storageClassName: {{ .Values.volumeClaim.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.volumeClaim.storage }}
