apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 120
          periodSeconds: 60
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 120
          periodSeconds: 60
        env:
        - name: SERILOG__MINIMUMLEVEL
          value: {{ .Values.loglevel }}
        - name: SERILOG__WRITETO__NAME
          value: "Console"

        - name: DATABASE__HOST
          value: {{ .Release.Name }}-postgis
        - name: DATABASE__PORT
          value: "5432"
        - name: DATABASE__DATABASE
          value: {{ .Values.database.database }}
        - name: DATABASE__USERNAME
          valueFrom:
            secretKeyRef:
              key: postgisUsername
              name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
        - name: DATABASE__PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgisPassword
              name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
        - name: DATABASE__SCHEMA
          value: route_network_validator
        - name: DATABASE__ELEMENTNOTFEEDEDTABLENAME
          value: element_not_feeded

        - name: NOTIFICATIONSERVER__DOMAIN
          value: {{ .Values.notificationServer.domain }}
        - name: NOTIFICATIONSERVER__PORT
          value: "{{ .Values.notificationServer.port }}"

        - name: EVENTSTORE__CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              key: eventStoreConnectionString
              name: {{ .Release.Name }}-{{ .Chart.Name }}-secret

      restartPolicy: Always
