apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 120
          periodSeconds: 60
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 120
          periodSeconds: 60
        env:
        - name: SERILOG__MINIMUMLEVEL__DEFAULT
          value: {{ .Values.loglevel }}
        - name: SERILOG__WRITETO__NAME
          value: "Console"

        - name: DATABASE__HOST
          value: {{ .Release.Name }}-postgis
        - name: DATABASE__PORT
          value: "5432"
        - name: DATABASE__DATABASE
          value: {{ .Values.database.database }}
        - name: DATABASE__USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis
        - name: DATABASE__PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis
        - name: DATABASE__SCHEMA
          value: route_network_validator
        - name: DATABASE__ELEMENTNOTFEEDEDTABLENAME
          value: element_not_feeded

        - name: KAFKA__SERVER
          value: {{ .Release.Name }}-kafka-cluster-kafka-bootstrap:9092
        - name: KAFKA__ROUTENETWORKEVENTTOPIC
          value: event.route-network
        - name: KAFKA__GEOGRAPHICALAREAUPDATEDTOPIC
          value: event.geographical-area-updated
        - name: KAFKA__POSITIONFILEPATH
          value: "/tmp/"
      restartPolicy: Always
