apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis
data:
  connectionString:{{ "User ID={{ .Values.database.username }};Password={{ .Values.database.password }};Database={{ .Values.database.database }};Server={{ .Release.Name }}-postgis;Port={{ .Values.database.port }}" | b64enc }}
