apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
data:
  postgisUsername: {{ .Values.postgis.username | b64enc }}
  postgisPassword: {{ .Values.postgis.password | b64enc }}
  eventStoreConnectionString: {{ .Values.eventStore.connectionString | b64enc }}
