loglevel: "Warning"
writeToName: "Console"

replicas: 1

database:
  database: OPEN_FTTH
  username: postgres
  password: postgres

image:
  repository: openftth/route-network-validator
  tag: v1.0.3
