apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 15
          periodSeconds: 15
        env:
        - name: SERILOG__MINIMUMLEVEL
          value: {{ .Values.loglevel }}

        - name: APPLICATION__APPLICATIONNAME
          value: {{ .Values.application.applicationName }}
        - name: APPLICATION__TOLERANCE
          value: "{{ .Values.application.tolerance }}"
        - name: APPLICATION__SENDGEOGRAPHICALAREAUPDATEDNOTIFICATION
          value: "{{ .Values.application.sendGeographicalAreaUpdatedNotification }}"
        - name: APPLICATION__ENABLESEGMENTENDSAUTOSNAPPINGTOROUTENODE
          value: "{{ .Values.application.enableSegmentEndsAutoSnappingToRouteNode }}"
        - name: APPLICATION__APIGATEWAYHOST
          value: http://{{ .Release.Name }}-api-gateway

        - name: POSTGIS__HOST
          value: {{ .Release.Name }}-postgis
        - name: POSTGIS__PORT
          value: "5432"
        - name: POSTGIS__DATABASE
          value: {{ .Values.postgis.database }}
        - name: POSTGIS__USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis
        - name: POSTGIS__PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis

        - name: KAFKA__SERVER
          value: {{ .Release.Name }}-kafka-cluster-kafka-bootstrap:9092
        - name: KAFKA__POSTGISROUTENETWORKTOPIC
          value: "postgres-connector.route-network"
        - name: KAFKA__POSTGISROUTENETWORKCONSUMER
          value: "postgres-connector-gdb-integrator-consumer"
        - name: KAFKA__EVENTROUTENETWORKTOPICNAME
          value: "domain.route-network"
        - name: KAFKA__EVENTGEOGRAPHICALAREAUPDATED
          value: "notification.geographical-area-updated"
      restartPolicy: Always
