apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: openftth/gdb-integrator:v0.1.1-alpha
        env:
        - name: POSTGIS__SERVER
          value: {{ .Release.Name }}-postgis
        - name: POSTGIS__PORT
          value: "5432"
        - name: POSTGIS__USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis
        - name: POSTGIS__PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis
        - name: KAFKA__SERVER
          value: {{ .Release.Name }}-kafka-cluster-kafka-bootstrap
