apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 15
          periodSeconds: 15
        env:
        - name: SERILOG__MINIMUMLEVEL__DEFAULT
          value: {{ .Values.loglevel }}
        - name: SERILOG__WRITETO__NAME
          value: "Console"

        - name: APPLICATION__APPLICATIONNAME
          value: {{ .Values.application.applicationName }}
        - name: APPLICATION__TOLERANCE
          value: "{{ .Values.application.tolerance }}"

        - name: POSTGIS__HOST
          value: {{ .Release.Name }}-postgis
        - name: POSTGIS__PORT
          value: "5432"
        - name: POSTGIS__DATABASE
          value: {{ .Values.postgis.database }}
        - name: POSTGIS__USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis
        - name: POSTGIS__PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ .Release.Name }}-{{ .Chart.Name }}-postgis

        - name: KAFKA__SERVER
          value: {{ .Release.Name }}-kafka-cluster-kafka-bootstrap:9092
        - name: KAFKA__POSTGISROUTENETWORKTOPIC
          value: "postgis.route-network"
        - name: KAFKA__POSTGISROUTENETWORKCONSUMER
          value: "postgis-route-network-consumer"
        - name: KAFKA__POSITIONFILEPATH
          value: "/data/"
        - name: KAFKA__EVENTROUTENETWORKTOPICNAME
          value: "event.route-network"
        volumeMounts:
        - mountPath: /data
          name: {{ .Release.Name }}-{{ .Chart.Name }}-data
      restartPolicy: Always
      volumes:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Chart.Name }}
