apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: janusgraph/janusgraph:{{ .Values.imageVersion }}
          env:
            - name: JANUS_PROPS_TEMPLATE
              value: {{ .Values.propsTemplate }}
            - name: janusgraph.storage.backend
              value: {{ .Values.storageBackend }}
            - name: janusgraph.storage.hostname
              value: {{ .Release.Name }}-cassandra
            - name: janusgraph.index.search.backend
              value: {{ .Values.searchBackend }}
            - name: janusgraph.index.search.hostname
              value: {{ .Release.Name }}-{{ .Values.searchHostname}}
            - name: janusgraph.index.search.elasticsearch.client-only
              value: "{{ .Values.elasticsearchClientOnly }}"
          ports:
            - containerPort: 8182
              protocol: TCP
              name: {{ .Chart.Name }}
          readinessProbe:
            exec:
              command:
                - bin/gremlin.sh
                - -e
                - scripts/remote-connect.groovy
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - bin/gremlin.sh
                - -e
                - scripts/remote-connect.groovy
            initialDelaySeconds: 5
            periodSeconds: 20
