apiVersion: apps/v1
kind: Deployment
metadata:
  name: janusgraph-deployment
  labels:
    app: janusgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: janusgraph
  template:
    metadata:
      labels:
        app: janusgraph
    spec:
      containers:
        - name: janusgraph
          image: janusgraph/janusgraph:0.5.2
          env:
            - name: JANUS_PROPS_TEMPLATE
              value: cassandra-es
            - name: janusgraph.storage.backend
              value: cql
            - name: janusgraph.storage.hostname
              value: openftth-cassandra
            - name: janusgraph.index.search.hostname
              value: elasticsearch-master
          ports:
            - containerPort: 8182
              name: janusgraph
