apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: janusgraph/janusgraph:0.5.2
          env:
            - name: JANUS_PROPS_TEMPLATE
              value: cassandra-es
            - name: janusgraph.storage.backend
              value: cql
            - name: janusgraph.storage.hostname
              value: {{ .Release.Name }}-cassandra
            - name: janusgraph.index.search.backend
              value: elasticsearch
            - name: janusgraph.index.search.hostname
              value: {{ .Release.Name }}-elasticsearch-master
            - name: janusgraph.index.search.elasticsearch.client-only
              value: "true"
          ports:
            - containerPort: 8182
              protocol: TCP
              name: {{ .Chart.Name }}
          readinessProbe:
            exec:
              command:
                - bin/gremlin.sh
                - -e
                - scripts/remote-connect.groovy
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - bin/gremlin.sh
                - -e
                - scripts/remote-connect.groovy
            initialDelaySeconds: 5
            periodSeconds: 20
