apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: 8182
      targetPort: 8182
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
