apiVersion: v1
kind: Service
metadata:
  name: janusgraph
  labels:
    app: janusgraph
spec:
  type: NodePort
  ports:
    - port: 8182
      targetPort: 8182
      protocol: TCP
  selector:
    app: janusgraph
