apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-cluster-status
  labels:
    strimzi.io/cluster: "{{ .Release.Name }}-kafka-cluster"
spec:
  config:
    cleanup.policy: compact
  partitions: 5
  replicas: 1
