apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: domain.route-network
  labels:
    strimzi.io/cluster: "{{ .Release.Name }}-kafka-cluster"
spec:
  config:
    retention.ms: -1
  partitions: {{ .Values.topics.domainRouteNetwork.partitions }}
  replicas: {{ .Values.topics.domainRouteNetwork.replicas }}
