apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: event.route-network
  labels:
    strimzi.io/cluster: "{{ .Release.Name }}-kafka-cluster"
spec:
  partitions: {{ .Values.topics.eventRouteNetwork.partitions }}
  replicas: {{ .Values.topics.eventRouteNetwork.replicas }}
