apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          deleteClaim: false
    config:
      offsets.topic.replication.factor: {{ .Values.kafka.config.replicationFactorOffsets }}
      transaction.state.log.replication.factor: {{ .Values.kafka.config.replicationFactorStatelog }}
      transaction.state.log.min.isr: {{ .Values.kafka.config.stateLogMinIsr }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
