apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: notification.utility-network
  labels:
    strimzi.io/cluster: "{{ .Release.Name }}-kafka-cluster"
spec:
  config:
    retention.ms: 14400000
  partitions: {{ .Values.topics.notificationUtilityNetwork.partitions }}
  replicas: {{ .Values.topics.notificationUtilityNetwork.replicas }}