version: 2.1

executors:
  helm-kubectl:
    docker:
    - image: dtzar/helm-kubectl

jobs:
  package-and-upload:
    executor: helm-kubectl
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b1:09:e2:11:d9:8e:a9:2e:1e:69:ff:76:db:32:7f:44"
      - run:
          name: key-scan
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: git clone charts
          command: git clone git@github.com:DAXGRID/charts.git
      - run:
          name: git clone open-ftth-chart
          command: git clone git@github.com:DAXGRID/open-ftth-chart.git
      - run:
          name: package and push
          command: |
             cd ./charts
             helm dependency build ../open-ftth-chart/openftth
             helm package ../open-ftth-chart/openftth
             helm repo index ./ --url https://daxgrid.github.io/charts/
             git config user.email "runeanielsen@live.dk"
             git config user.name "runeanielsen"
             git add .
             git commit -m "adds/updates $(ls -t open* | head -1)"
             git push
workflows:
  package-and-upload-chart:
    jobs:
      - package-and-upload:
          filters:
            tags:
              only: /.*/
