replicas: 1
serviceType: LoadBalancer

image:
  repository: openftth/frontend
  tag: v5.12.1

mapbox:
  apiKey: ""
  styleUrl: ""

desktopBridgeUri: ""
apiGatewayHttpUri: ""
apiGatewayWsUri: ""
keyCloakUri: ""
routeNetworkTileServerUri: ""
aerialPhotoServerUri: ""
basemapTileServerUri: ""
colorMarkings:
  - Blue
  - Red
  - Green
