postgis:
  database: OPEN_FTTH
  username: postgres
  password: postgres

replicas: 1
loglevel: "Information"

resources:
  requests:
    memory: 300Mi

application:
  tolerance: "0.01"
  applicationName: "GDB_INTEGRATOR"
  sendGeographicalAreaUpdatedNotification: true
  enableSegmentEndsAutoSnappingToRouteNode: true

image:
  repository: openftth/gdb-integrator
  tag: v4.5.7
