postgis:
  database: OPEN_FTTH
  username: postgres
  password: postgres

replicas: 1
storage: 1Gi
storageClassName: ""
loglevel: "Information"
backup: true

resources:
 requests:
   memory: 300Mi

application:
  tolerance: "0.01"
  applicationName: "GDB_INTEGRATOR"
  sendGeographicalAreaUpdatedNotification: true
  enableSegmentEndsAutoSnappingToRouteNode: true

image:
  repository: openftth/gdb-integrator
  tag: v2.3.3
