postgis:
  database: OPEN_FTTH
  username: postgres
  password: postgres

replicas: 1
loglevel: "Information"

resources:
  requests:
    memory: 300Mi

application:
  tolerance: "0.01"
  applicationName: "GDB_INTEGRATOR"
  sendGeographicalAreaUpdatedNotification: true
  enableSegmentEndsAutoSnappingToRouteNode: true

notificationServer:
  domain: "notification-server"
  port: 80

eventStore:
  connectionString: "Host=openftth-event-store-postgresql;Port=5432;Username=postgres;Password=postgres;Database=EVENT_STORE"

image:
  repository: openftth/gdb-integrator
  tag: v6.0.3
