postgis:
  database: OPEN_FTTH
  username: postgres
  password: postgres

replicas: 1
storage: 1Gi
storageClassName: ""
loglevel: "Information"

application:
  tolerance: "0.01"
  applicationName: "GDB_INTEGRATOR"

image:
  repository: openftth/gdb-integrator
  tag: v1.2.0
