postgis:
  database: OPEN_FTTH
  username: postgres
  password: postgres

replicas: 1
storage: 1Gi
storageClassName: ""
loglevel: "Information"

resources:
 requests:
   memory: 300Mi

application:
  tolerance: "0.01"
  applicationName: "GDB_INTEGRATOR"

image:
  repository: openftth/gdb-integrator
  tag: v2.1.1
