apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 120
          periodSeconds: 60
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 180
          periodSeconds: 60
        env:
        - name: LOGGING__LOGLEVEL_DEFAULT
          value: {{ .Values.loglevel }}

        - name: KAFKA__SERVER
          value: {{ .Release.Name }}-kafka-cluster-kafka-bootstrap:9092
        - name: KAFKA__POSITIONFILEPATH
          value: "/data/"
        - name: KAFKA__ROUTENETWORKEVENTTOPIC
          value: "domain.route-network"
        - name: KAFKA__UTILITYNETWORKNOTIFICATIONSTOPIC
          value: "notification.utility-network"
        - name: REMOTESERVICES__ROUTENETWORKSERVICE
          value: http://{{ .Release.Name }}-route-network-service
        {{- if .Values.database.name }}
        - name: DATABASE__HOST
          value: {{ .Release.Name }}-postgis-basemap
        - name: DATABASE__PORT
          value: "5432"
        - name: DATABASE__DATABASE
          value: {{ .Values.database.name }}
        - name: DATABASE__USERNAME
          value: {{ .Values.database.username }}
        - name: DATABASE__PASSWORD
          value: {{ .Values.database.password }}
        {{ end }}

        volumeMounts:
        - mountPath: /data
          name: {{ .Release.Name }}-{{ .Chart.Name }}-data
      restartPolicy: Always
      volumes:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Chart.Name }}
