apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          failureThreshold: 60
          timeoutSeconds: 10
        env:
        - name: SERILOG__LOGLEVEL__DEFAULT
          value: {{ .Values.loglevel }}

        - name: KAFKA__SERVER
          value: {{ .Release.Name }}-kafka-cluster-kafka-bootstrap:9092
        - name: KAFKA__POSITIONFILEPATH
          value: "/data/"
        - name: KAFKA__ROUTENETWORKEVENTTOPIC
          value: "domain.route-network"
        - name: KAFKA__UTILITYNETWORKNOTIFICATIONSTOPIC
          value: "notification.utility-network"
        - name: REMOTESERVICES__ROUTENETWORKSERVICE
          value: http://{{ .Release.Name }}-route-network-service

        - name: EVENTSTOREDATABASE__HOST
          value: openftth-event-store-postgresql
        - name: EVENTSTOREDATABASE__PORT
          value: "5432"
        - name: EVENTSTOREDATABASE__DATABASE
          value: {{ .Values.eventStoreDatabase.name }}
        - name: EVENTSTOREDATABASE__USERNAME
          value: {{ .Values.eventStoreDatabase.username }}
        - name: EVENTSTOREDATABASE__PASSWORD
          value: {{ .Values.eventStoreDatabase.password }}

        - name: GEODATABASE__HOST
          value: {{ .Release.Name }}-postgis
        - name: GEODATABASE__PORT
          value: "5432"
        - name: GEODATABASE__DATABASE
          value: {{ .Values.geoDatabase.name }}
        - name: GEODATABASE__USERNAME
          value: {{ .Values.geoDatabase.username }}
        - name: GEODATABASE__PASSWORD
          value: {{ .Values.geoDatabase.password }}

        - name: TYPESENSE__HOST
          value: {{ .Values.typesense.host }}
        - name: TYPESENSE__PORT
          value: "{{ .Values.typesense.port }}"
        - name: TYPESENSE__APIKEY
          value: {{ .Values.typesense.apiKey }}

        - name: AUTH__HOST
          value: {{ .Values.auth.host }}
        - name: AUTH__REQUIREHTTPS
          value: "{{ .Values.auth.requireHttps }}"
        - name: AUTH__ENABLE
          value: "{{ .Values.auth.enable }}"
        - name: AUTH__AUDIENCE
          value: {{ .Values.auth.audience }}

        - name: OUTAGESERVICE__OUTAGESERVICEURL
          value: {{ .Values.outageService.outageServiceUrl }}

        - name: NOTIFICATIONSERVER__DOMAIN
          value: {{ .Values.notificationServer.domain }}
        - name: NOTIFICATIONSERVER__PORT
          value: "{{ .Values.notificationServer.port }}"

      restartPolicy: Always
