apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
        backup: "{{ .Values.backup }}"
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: LOGGING__LOGLEVEL_DEFAULT
          value: {{ .Values.loglevel }}
        - name: KAFKA__SERVER
          value: {{ .Release.Name }}-kafka-cluster-kafka-bootstrap:9092
        - name: KAFKA__POSITIONFILEPATH
          value: "/data/"
        - name: KAFKA__ROUTENETWORKEVENTTOPIC
          value: "event.route-network"
        - name: REMOTESERVICES__ROUTENETWORKSERVICE
          value: http://{{ .Release.Name }}-route-network-service
        volumeMounts:
        - mountPath: /data
          name: {{ .Release.Name }}-{{ .Chart.Name }}-data
      restartPolicy: Always
      volumes:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Chart.Name }}
