apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
