apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-cluster
spec:
  image: openftth/connect-debezium-postgresql:1.7.0.Final
  replicas: {{ .Values.replicas }}
  bootstrapServers: {{ .Release.Name }}-{{ .Values.bootstrapServers }}
  tls:
    trustedCertificates:
      - secretName: {{ .Release.Name }}-{{ .Values.tls.trustedCertificates.secretName }}
        certificate: {{ .Values.tls.trustedCertificates.certificate }}
  config:
    config.storage.replication.factor: {{ .Values.replicationFactor.config }}
    offset.storage.replication.factor: {{ .Values.replicationFactor.offset }}
    status.storage.replication.factor: {{ .Values.replicationFactor.status }}
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  externalConfiguration:
    volumes:
      - name: connector-config
        secret:
          secretName: {{ .Release.Name }}-{{ .Chart.Name }}
