apiVersion: "kafka.strimzi.io/v1beta2"
kind: KafkaConnector
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-connector
  labels:
    strimzi.io/cluster: {{ .Release.Name }}-{{ .Chart.Name }}-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: {{ .Release.Name }}-postgis
    database.port: "5432"
    database.user: "${file:/opt/kafka/external-configuration/connector-config/debezium-postgres-credentials.properties:username}"
    database.password: "${file:/opt/kafka/external-configuration/connector-config/debezium-postgres-credentials.properties:password}"
    database.server.name: "postgres"
    database.dbname: "OPEN_FTTH"
    database.whitelist: "OPEN_FTTH"
    database.history.kafka.bootstrap.servers: "{{ .Release.Name }}-kafka-cluster-kafka-bootstrap:9092"
    database.history.kafka.topic: "schema-changes.OPEN_FTTH"
    schema.whitelist: "route_network"
    include.schema.changes: "true"
    plugin.name: "pgoutput"
    transforms: "Combine"
    transforms.Combine.type: "io.debezium.transforms.ByLogicalTableRouter"
    transforms.Combine.topic.regex: "(.*)"
    transforms.Combine.topic.replacement: "postgres-connector.route-network"
    heartbeat.interval.ms: 3000
