apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
stringData:
  debezium-postgres-credentials.properties: |-
    username: {{ .Values.postgis.username }}
    password: {{ .Values.postgis.password }}
