backup: true
zookeeper:
  replicas: 1
  storage:
    size: 10Gi
    deleteClaim: true
    storageClassName: ""
kafka:
  replicas: 1
  config:
    autoCreateTopicsEnable: true
    replicationFactorOffsets: 1
    replicationFactorStatelog: 1
    stateLogMinIsr: 1
  external:
    type: nodeport
    tls: false
  storage:
    storageClassName: ""
    size: 10Gi
    deleteClaim: true
topics:
  domainRouteNetwork:
    partitions: 1
    replicas: 1
  requestRouteNetwork:
    partitions: 1
    replicas: 1
  postgresConnectorRouteNetwork:
    partitions: 1
    replicas: 1
  notificationGeoGraphicalAreaUpdated:
    partitions: 1
    replicas: 1
