zookeeper:
  replicas: 1
  storage:
    size: 10Gi
    deleteClaim: true
    storageClassName: ""
kafka:
  replicas: 1
  config:
    autoCreateTopicsEnable: false
    replicationFactorOffsets: 1
    replicationFactorStatelog: 1
    stateLogMinIsr: 1
  # Makes the Kafka broker external.
  # external:
  #   type: loadbalancer
  #   tls: true
  storage:
    storageClassName: ""
    size: 10Gi
    deleteClaim: false
topics:
  domainRouteNetwork:
    partitions: 1
    replicas: 1
  requestRouteNetwork:
    partitions: 1
    replicas: 1
  postgresConnectorRouteNetwork:
    partitions: 1
    replicas: 1
  notificationGeoGraphicalAreaUpdated:
    partitions: 1
    replicas: 1
  notificationUtilityNetwork:
    partitions: 1
    replicas: 1
  notificationFileChanges:
    partitions: 1
    replicas: 1
