apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
  annotations: {{ toYaml .Values.serviceAnnotations | nindent 4 }}
spec:
  ports:
    - name: https
      port: 5432
      targetPort: 5432
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
