apiVersion: v2
name: openftth
appVersion: "1.0"
description: A Helm chart for openftth 1.0
version: 0.1.0
type: application
dependencies:
  - name: cassandra
    version: 5.4.0
    repository: https://charts.bitnami.com/bitnami
  - name: elasticsearch
    version: 7.7.1
    repository: https://helm.elastic.co
  - name: nginx-ingress-controller
    version: 5.3.24
    repository: https://charts.bitnami.com/bitnami
