apiVersion: v2
name: openftth
appVersion: "0.2.9"
description: A Helm chart for openftth
version: 0.2.18
type: application
dependencies:
  - name: cassandra
    version: 5.6.1
    repository: https://charts.bitnami.com/bitnami
