apiVersion: v2
name: openftth
appVersion: "1.0"
description: A Helm chart for openftth 1.0
version: 0.1.0
type: application
dependencies:
  - name: cassandra
    version: 0.15.1
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: elasticsearch
    version: 6.8.10
    repository: https://helm.elastic.co
