apiVersion: v2
name: openftth
appVersion: "0.2.3"
description: A Helm chart for openftth
version: 0.2.10
type: application
dependencies:
  - name: cassandra
    version: 5.6.1
    repository: https://charts.bitnami.com/bitnami
