postgis:
  username: postgres
  password: postgres
  serviceType: LoadBalancer
  serviceAnnotations: {}
  volumeClaim:
    storageClassName: ""
    storage: 10Gi
  resources:
    requests:
      memory: 1Gi
