############################
# Cassandra
############################
cassandra:
  config:
    cluster_size: 1

############################
# ElasticSearch
############################
elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
