############################
# Cassandra
############################
cassandra:
  config:
    cluster_size: 1
    seed_size: 1

############################
# ElasticSearch
############################
elasticsearch:
  clusterName: openftth-elasticsearch
  replicas: 1
  minimumMasterNodes: 1
  antiAffinity: "soft"
