cassandra:
  cluster:
    name: cassandra
    replicaCount: 3
  dbUser:
    user: cassandra
    password:
    forcePassword: true

strimzi:
  zookeeper:
    replicas: 3
    storage:
      size: 100Gi
      deleteClaim: true
  kafka:
    replicas: 3
    config:
      replicationFactorOffsets: 3
      replicationFactorStateLog: 3
      stateLogMinIsr: 2
    volumes:
      size: 100Gi
      deleteClaim: true
  external:
    type: loadbalancer
    tls: true
  topics:
    eventRouteNetwork:
      partitions: 1
      replicas: 3
    requestRouteNetwork:
      partitions: 1
      replicas: 3

gdb-integrator:
  replicas: 1
  loglevel: "Information"
  postgis:
    username: postgres
    password: postgres
  application:
    tolerance: "0.1"
    applicationName: "GDB_INTEGRATOR"

postgis-connector:
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9093
  replicationFactor:
    config: 1
    offset: 1
    status: 1
  tls:
    trustedCertificates:
      secretName: kafka-cluster-cluster-ca-cert
      certificate: ca.crt
  postgis:
    username: postgres
    password:

postgis:
  username: postgres
  password:
  serviceType: LoadBalancer
