api-gateway:
  replicas: 1
  loglevel: "Information"
  eventStoreDatabase:
    name: EVENT_STORE
    username: postgres
    password: postgres
  geoDatabase:
    name: OPEN_FTTH
    username: postgres
    password: postgres
  typesense:
    host: openftth-search-typesense
    apiKey: changeMe!
  auth:
    host: http://auth.openftth.local/auth/realms/openftth
    requireHttps: false
    audience: "account"
    enable: true

frontend:
  replicas: 1
  desktopBridgeUri: "ws://desktop-bridge.openftth.local"
  apiGatewayHttpUri: "http://api-gateway.openftth.local"
  apiGatewayWsUri: "ws://api-gateway.openftth.local"
  keyCloakUri: "http://auth.openftth.local/auth"
  routeNetworkTileServerUri: "http://tiles-routenetwork.openftth.local"
  basemapTileServerUri: "http://tiles-basemap.openftth.local"
  layers:
    - name: aerial-photo
      layerGroups:
        - text: Aerial Photo
          layers:
            - aerial_photo
  informationControlConfig:
    sourceLayers:
      - body: |
          <div>
            <p>Id: {id}</p>
            <p>Mrid: {properties.mrid}</p>
          </div>
        layer: route_network
        filter:
          property: properties.objecttype
          value: route_node
  maplibreJson: ""

postgis:
  username: postgres
  password: postgres
  serviceType: LoadBalancer
  serviceAnnotations: {}
  volumeClaim:
    storageClassName: ""
    storage: 10Gi
  resources:
    requests:
      memory: 1Gi

ingress:
  tls:
    enabled: false
    acme:
      email: ""
      server: ""
    hosts: {}
  domainNames:
    frontend: openftth.local
    apiGateway: api-gateway.openftth.local
    auth: auth.openftth.local
