cassandra:
  cluster:
    name: cassandra
    replicaCount: 1
  dbUser:
    user: cassandra
    forcePassword: false
    password: cassandra

strimzi:
  zookeeper:
    replicas: 1
    storage:
      size: 10Gi
      deleteClaim: true
  kafka:
    replicas: 1
    config:
      autoCreateTopicsEnable: true
      replicationFactorOffsets: 1
      replicationFactorStatelog: 1
      stateLogMinIsr: 1
    external:
      type: nodeport
      tls: false
    volumes:
      size: 10Gi
      deleteClaim: true
  topics:
    eventRouteNetwork:
      partitions: 1
      replicas: 1
    requestRouteNetwork:
      partitions: 1
      replicas: 1

gdb-integrator:
  replicas: 1
  loglevel: "Information"
  postgis:
    username: postgres
    password: postgres
  application:
    tolerance: "0.1"
    applicationName: "GDB_INTEGRATOR"

postgis-connector:
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9093
  replicationFactor:
    config: 1
    offset: 1
    status: 1
  tls:
    trustedCertificates:
      secretName: kafka-cluster-cluster-ca-cert
      certificate: ca.crt
  postgis:
    username: postgres
    password: postgres

postgis:
  username: postgres
  password: postgres
  serviceType: LoadBalancer
