############################
# Cassandra
############################
cassandra:
  dbUser:
    user: cassandra
    forcePassword: false
    password: cassandra

############################
# ElasticSearch
############################
elasticsearch:
  clusterName: openftth-elasticsearch
  replicas: 1
  minimumMasterNodes: 1
  antiAffinity: "soft"
