cassandra:
  cluster:
    name: cassandra
    replicaCount: 1
    seedCount: 1
  dbUser:
    user: cassandra
    forcePassword: false
    password: cassandra
  persistence:
    storageClass: ""

strimzi:
  zookeeper:
    replicas: 1
    storage:
      size: 10Gi
      deleteClaim: true
  kafka:
    replicas: 1
    config:
      autoCreateTopicsEnable: true
      replicationFactorOffsets: 1
      replicationFactorStatelog: 1
      stateLogMinIsr: 1
    external:
      type: nodeport
      tls: false
    volumes:
      size: 10Gi
      deleteClaim: true
  topics:
    eventRouteNetwork:
      partitions: 1
      replicas: 1
    requestRouteNetwork:
      partitions: 1
      replicas: 1

api-gateway:
  replicas: 1
  storage: 1Gi
  loglevel: "Warning"
  serviceType: LoadBalancer
  storageClassName: ""

route-network-validator:
  loglevel: "Warning"
  writeToName: "Console"
  replicas: 1

  database:
    database: OPEN_FTTH
    username: postgres
    password: postgres
    port: 5432

route-network-service:
  replicas: 1
  loglevel: "Warning"

gdb-integrator:
  replicas: 1
  loglevel: "Warning"
  storage: 1Gi
  postgis:
    username: postgres
    password: postgres
  application:
    tolerance: "0.01"
    applicationName: "GDB_INTEGRATOR"

postgis-connector:
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9093
  replicationFactor:
    config: 1
    offset: 1
    status: 1
  tls:
    trustedCertificates:
      secretName: kafka-cluster-cluster-ca-cert
      certificate: ca.crt
  postgis:
    username: postgres
    password: postgres

postgis:
  username: postgres
  password: postgres
  serviceType: LoadBalancer
  volumeClaim:
    storageClassName: ""
    storage: 10Gi
