cassandra:
  cluster:
    name: cassandra
    replicaCount: 3
    seedCount: 2
  dbUser:
    user: cassandra
    password:
    forcePassword: true
  persistence:
    storageClass: ""

strimzi:
  zookeeper:
    replicas: 3
    storage:
      size: 10Gi
      deleteClaim: false
      storageClassName: ""
  kafka:
    replicas: 3
    config:
      autoCreateTopicsEnable: true
      replicationFactorOffsets: 3
      replicationFactorStateLog: 3
      stateLogMinIsr: 2
    storage:
      storageClassName: ""
      size: 10Gi
      deleteClaim: false
    external:
      type: ""
      tls: true
  topics:
    eventRouteNetwork:
      partitions: 1
      replicas: 3
    requestRouteNetwork:
      partitions: 1
      replicas: 3
    postgisRouteNetwork:
      partitions: 1
      replicas: 3
    eventGeoGraphicalAreaUpdated:
      partitions: 1
      replicas: 3

api-gateway:
  replicas: 1
  storage: 1Gi
  loglevel: "Information"
  serviceType: LoadBalancer
  storageClassName: ""

route-network-validator:
  loglevel: "Information"
  replicas: 1

  database:
    database: OPEN_FTTH
    username: postgres
    password: postgres
    port: 5432

route-network-service:
  replicas: 2
  loglevel: "Information"

gdb-integrator:
  replicas: 1
  loglevel: "Information"
  storage: 1Gi
  postgis:
    username: postgres
    password: postgres
  application:
    tolerance: "0.01"
    applicationName: "GDB_INTEGRATOR"

postgis-connector:
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9093
  replicationFactor:
    config: 1
    offset: 1
    status: 1
  tls:
    trustedCertificates:
      secretName: kafka-cluster-cluster-ca-cert
      certificate: ca.crt
  postgis:
    username: postgres
    password:

frontend:
  replicas: 1
  serviceType: LoadBalancer

postgis:
  username: postgres
  password:
  serviceType: LoadBalancer
  volumeClaim:
    storageClassName: ""
    storage: 10Gi

frontend:
  graphqlServer:
