strimzi:
  zookeeper:
    replicas: 1
    storage:
      size: 10Gi
      deleteClaim: true
      storageClassName: ""
  kafka:
    replicas: 1
    config:
      autoCreateTopicsEnable: false
      replicationFactorOffsets: 1
      replicationFactorStatelog: 1
      stateLogMinIsr: 1
    storage:
      storageClassName: ""
      size: 10Gi
      deleteClaim: false
    external:
      type: nodeport
      tls: false
  topics:
    domainRouteNetwork:
      partitions: 1
      replicas: 1
    requestRouteNetwork:
      partitions: 1
      replicas: 1
    postgresConnectorRouteNetwork:
      partitions: 1
      replicas: 1
    notificationGeoGraphicalAreaUpdated:
      partitions: 1
      replicas: 1
    notificationUtilityNetwork:
      partitions: 1
      replicas: 1

api-gateway:
  replicas: 1
  loglevel: "Information"
  eventStoreDatabase:
    name: EVENT_STORE
    username: postgres
    password: postgres
  geoDatabase:
    name: OPEN_FTTH
    username: postgres
    password: postgres
  auth:
    host: http://auth.openftth.local/auth/realms/openftth
    requireHttps: false
    audience: "account"
    enable: true

route-network-validator:
  loglevel: "Information"
  replicas: 1
  resources:
    requests:
      memory: 0Mi
    limits:
      memory: 0Gi

  database:
    database: OPEN_FTTH
    username: postgres
    password: postgres
    port: 5432

gdb-integrator:
  replicas: 1
  loglevel: "Information"
  storage: 1Gi
  postgis:
    username: postgres
    password: postgres
  application:
    tolerance: "0.01"
    applicationName: "GDB_INTEGRATOR"
    sendGeographicalAreaUpdatedNotification: true
    enableSegmentEndsAutoSnappingToRouteNode: true
  resources:
    requests:
      memory: 0Mi

postgis-connector:
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9093
  replicationFactor:
    config: 1
    offset: 1
    status: 1
  tls:
    trustedCertificates:
      secretName: kafka-cluster-cluster-ca-cert
      certificate: ca.crt
  postgis:
    username: postgres
    password: postgres

frontend:
  replicas: 1
  desktopBridgeUri: "ws://desktop-bridge.openftth.local"
  apiGatewayHttpUri: "http://api-gateway.openftth.local"
  apiGatewayWsUri: "ws://api-gateway.openftth.local"
  keyCloakUri: "http://auth.openftth.local/auth"
  routeNetworkTileServerUri: "http://tiles-routenetwork.openftth.local"
  basemapTileServerUri: "http://tiles-basemap.openftth.local"

postgis:
  username: postgres
  password: postgres
  serviceType: LoadBalancer
  serviceAnnotations: {}
  volumeClaim:
    storageClassName: ""
    storage: 10Gi

desktop-bridge:
  replicas: 1
  loglevel: "Information"

ingress:
  tls:
    enabled: false
    acme:
      email: ""
      server: ""
    hosts: {}
  domainNames:
    frontend: openftth.local
    desktopBridge: desktop-bridge.openftth.local
    apiGateway: api-gateway.openftth.local
    auth: auth.openftth.local
    tileServerRouteNetwork: tiles-routenetwork.openftth.local
    tileServerBasemap: tiles-basemap.openftth.local
