apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      volumes:
       - name: {{ .Release.Name }}-{{ .Chart.Name }}-mnt
         configMap:
           name: {{ .Release.Name }}-{{ .Chart.Name }}
           items:
           - key: config-env.js
             path: config-env.js
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        volumeMounts:
         - name: {{ .Release.Name }}-{{ .Chart.Name }}-mnt
           mountPath: /usr/share/nginx/html/config-env.js
           subPath: config-env.js
      restartPolicy: Always
