username: postgres
password: postgres

serviceType: LoadBalancer

image:
  repository: kartoza/postgis
  tag: 12.4

volumeClaim:
  storageClassName: ""
  storage: 10Gi

resources:
  requests:
    memory: 1Gi

serviceAnnotations: {}
