apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    {{ if (eq .Values.ingress.tls.enabled true) }}
    cert-manager.io/cluster-issuer: letsencrypt
    {{ end }}
spec:
  {{ if (eq .Values.ingress.tls.enabled true) }}
  tls:
  - hosts: {{ toYaml .Values.ingress.tls.hosts | nindent 4 }}
    secretName: tls-secret
  {{ end }}
  rules:
  - host: {{ .Values.ingress.domainNames.frontend }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name}}-frontend
            port:
              number: 80
  - host: {{ .Values.ingress.domainNames.apiGateway }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name}}-api-gateway
            port:
              number: 80
  - host: {{ .Values.ingress.domainNames.auth }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 80
