{{ if (eq .Values.ingress.tls true) }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-letsencrypt
spec:
  acme:
    server: {{ .Values.tls.server }}
    email: {{ .Values.tls.email }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
{{ end }}