{{ if (eq .Values.ingress.tls.enabled true) }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: {{ .Values.ingress.tls.acme.server }}
    email: {{ .Values.ingress.tls.acme.email }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
{{ end }}